"""
core/rbac.py
------------
Role-Based Access Control (RBAC) definitions and centralized Permission Matrix.

Sprint 4A: Identity & Role-Based Access Control
Sprint 4B: Dual-Control Approval & Policy Governance Workflow
Provides:
- Strongly typed Role and Permission enumerations
- Centralized, auditable Role-to-Permission mapping matrix
- Authorization evaluation functions
"""

from enum import Enum
from typing import Dict, List, Set


class Role(str, Enum):
    """System roles governing access and governance authority."""
    ADMIN = "ADMIN"
    POLICY_AUTHOR = "POLICY_AUTHOR"
    POLICY_REVIEWER = "POLICY_REVIEWER"
    SECURITY_ANALYST = "SECURITY_ANALYST"
    AUDITOR = "AUDITOR"
    VIEWER = "VIEWER"


class Permission(str, Enum):
    """Granular system permissions."""
    # User Management
    USER_READ = "USER_READ"
    USER_MANAGE = "USER_MANAGE"

    # Evidence Vault
    EVIDENCE_INGEST = "EVIDENCE_INGEST"
    EVIDENCE_READ = "EVIDENCE_READ"

    # Normalization
    EVENT_NORMALIZE = "EVENT_NORMALIZE"
    NORMALIZED_EVENT_READ = "NORMALIZED_EVENT_READ"

    # Semantic Interpretation
    SEMANTIC_INTERPRET = "SEMANTIC_INTERPRET"

    # Semantic Policy Registry & Authoring
    SEMANTIC_POLICY_CREATE = "SEMANTIC_POLICY_CREATE"
    SEMANTIC_POLICY_EDIT_DRAFT = "SEMANTIC_POLICY_EDIT_DRAFT"
    SEMANTIC_POLICY_READ = "SEMANTIC_POLICY_READ"
    SEMANTIC_POLICY_COMPARE = "SEMANTIC_POLICY_COMPARE"
    SEMANTIC_POLICY_SUBMIT = "SEMANTIC_POLICY_SUBMIT"

    # Dual-Control Policy Governance & Review (Sprint 4B)
    POLICY_REVIEW = "POLICY_REVIEW"
    POLICY_APPROVE = "POLICY_APPROVE"
    POLICY_REJECT = "POLICY_REJECT"
    POLICY_ACTIVATE = "POLICY_ACTIVATE"
    GOVERNANCE_AUDIT_READ = "GOVERNANCE_AUDIT_READ"

    # Drift & Risk Alerts
    DRIFT_ALERT_READ = "DRIFT_ALERT_READ"

    # Audit & Provenance Trace
    AUDIT_READ = "AUDIT_READ"

    # Merkle Tree & Inclusion Proofs (Sprint 5B)
    MERKLE_BATCH_CREATE = "MERKLE_BATCH_CREATE"
    MERKLE_BATCH_READ = "MERKLE_BATCH_READ"
    MERKLE_PROOF_READ = "MERKLE_PROOF_READ"

    # Detection Rule Registry (Sprint 6A)
    DETECTION_RULE_CREATE = "DETECTION_RULE_CREATE"
    DETECTION_RULE_READ = "DETECTION_RULE_READ"

    # Detection Rule Trust & Semantic Drift Binding (Sprint 6B)
    DETECTION_RULE_TRUST_EVALUATE = "DETECTION_RULE_TRUST_EVALUATE"
    DETECTION_RULE_TRUST_READ = "DETECTION_RULE_TRUST_READ"
    DETECTION_TRUST_ALERT_READ = "DETECTION_TRUST_ALERT_READ"

    # Detection Rule Governance & Versioning (Sprint 6C)
    DETECTION_RULE_VERSION_CREATE = "DETECTION_RULE_VERSION_CREATE"
    DETECTION_RULE_VERSION_READ = "DETECTION_RULE_VERSION_READ"
    DETECTION_RULE_SUBMIT_REVIEW = "DETECTION_RULE_SUBMIT_REVIEW"
    DETECTION_RULE_REVIEW = "DETECTION_RULE_REVIEW"
    DETECTION_RULE_ACTIVATE = "DETECTION_RULE_ACTIVATE"
    DETECTION_RULE_DISABLE = "DETECTION_RULE_DISABLE"
    DETECTION_RULE_GOVERNANCE_READ = "DETECTION_RULE_GOVERNANCE_READ"

    # Detection Rule Execution Engine (Sprint 7A)
    DETECTION_EXECUTE = "DETECTION_EXECUTE"
    DETECTION_EXECUTION_READ = "DETECTION_EXECUTION_READ"

    # Risk Correlation & Prioritized Remediation (Sprint 7B)
    RISK_CORRELATION_READ = "RISK_CORRELATION_READ"
    RISK_CORRELATION_ANALYZE = "RISK_CORRELATION_ANALYZE"
    REMEDIATION_READ = "REMEDIATION_READ"
    REMEDIATION_GENERATE = "REMEDIATION_GENERATE"
    REMEDIATION_SIMULATE = "REMEDIATION_SIMULATE"
    REMEDIATION_MANAGE = "REMEDIATION_MANAGE"

    # Security Incident Correlation & Investigation (Sprint 8A)
    INCIDENT_READ = "INCIDENT_READ"
    INCIDENT_CREATE = "INCIDENT_CREATE"
    INCIDENT_ASSIGN = "INCIDENT_ASSIGN"
    INCIDENT_STATUS_UPDATE = "INCIDENT_STATUS_UPDATE"
    INCIDENT_SIGNAL_LINK = "INCIDENT_SIGNAL_LINK"
    INCIDENT_EVIDENCE_LINK = "INCIDENT_EVIDENCE_LINK"
    INCIDENT_FINDING_CREATE = "INCIDENT_FINDING_CREATE"
    INCIDENT_FINDING_REVIEW = "INCIDENT_FINDING_REVIEW"
    INCIDENT_AUDIT_READ = "INCIDENT_AUDIT_READ"

    # Incident Response Governance & Human Authorization (Sprint 8B)
    INCIDENT_RESPONSE_READ = "INCIDENT_RESPONSE_READ"
    INCIDENT_RESPONSE_RECOMMEND = "INCIDENT_RESPONSE_RECOMMEND"
    INCIDENT_CONTAINMENT_PROPOSE = "INCIDENT_CONTAINMENT_PROPOSE"
    INCIDENT_CONTAINMENT_REVIEW = "INCIDENT_CONTAINMENT_REVIEW"
    INCIDENT_RESPONSE_EXECUTE = "INCIDENT_RESPONSE_EXECUTE"
    INCIDENT_RESPONSE_VERIFY = "INCIDENT_RESPONSE_VERIFY"
    INCIDENT_RESPONSE_AUDIT = "INCIDENT_RESPONSE_AUDIT"

    # Continuous Security Assurance & Platform Health (Sprint 9A)
    ASSURANCE_READ = "ASSURANCE_READ"
    ASSURANCE_EVALUATE = "ASSURANCE_EVALUATE"
    ASSURANCE_ALERT_READ = "ASSURANCE_ALERT_READ"
    ASSURANCE_ALERT_TRIAGE = "ASSURANCE_ALERT_TRIAGE"
    ASSURANCE_AUDIT = "ASSURANCE_AUDIT"

    # Continuous Assurance Governance & Remediation (Sprint 9B)
    ASSURANCE_REMEDIATION_READ = "ASSURANCE_REMEDIATION_READ"
    ASSURANCE_REMEDIATION_CREATE = "ASSURANCE_REMEDIATION_CREATE"
    ASSURANCE_ROOT_CAUSE_ANALYZE = "ASSURANCE_ROOT_CAUSE_ANALYZE"
    ASSURANCE_REMEDIATION_RECOMMEND = "ASSURANCE_REMEDIATION_RECOMMEND"
    ASSURANCE_REMEDIATION_PLAN = "ASSURANCE_REMEDIATION_PLAN"
    ASSURANCE_REMEDIATION_REVIEW = "ASSURANCE_REMEDIATION_REVIEW"
    ASSURANCE_REMEDIATION_EXECUTE = "ASSURANCE_REMEDIATION_EXECUTE"
    ASSURANCE_RECOVERY_VERIFY = "ASSURANCE_RECOVERY_VERIFY"
    ASSURANCE_RECOVERY_CONFIRM = "ASSURANCE_RECOVERY_CONFIRM"
    ASSURANCE_REMEDIATION_AUDIT = "ASSURANCE_REMEDIATION_AUDIT"

    # Unified Security Intelligence & Executive Risk Posture (Sprint 10A)
    EXECUTIVE_SECURITY_READ = "EXECUTIVE_SECURITY_READ"
    EXECUTIVE_SECURITY_EVALUATE = "EXECUTIVE_SECURITY_EVALUATE"
    EXECUTIVE_SECURITY_EXPLAIN = "EXECUTIVE_SECURITY_EXPLAIN"
    EXECUTIVE_SECURITY_TREND_READ = "EXECUTIVE_SECURITY_TREND_READ"
    EXECUTIVE_SECURITY_PROVENANCE_READ = "EXECUTIVE_SECURITY_PROVENANCE_READ"
    EXECUTIVE_SECURITY_AUDIT = "EXECUTIVE_SECURITY_AUDIT"

    # End-to-End Security Scenario Orchestration & Evidence Replay (Sprint 10B)
    SCENARIO_READ = "SCENARIO_READ"
    SCENARIO_CREATE = "SCENARIO_CREATE"
    SCENARIO_VERSION_MANAGE = "SCENARIO_VERSION_MANAGE"
    SCENARIO_EXECUTE = "SCENARIO_EXECUTE"
    SCENARIO_REPLAY = "SCENARIO_REPLAY"
    SCENARIO_VERIFY = "SCENARIO_VERIFY"
    SCENARIO_PROVENANCE_READ = "SCENARIO_PROVENANCE_READ"
    SCENARIO_AUDIT = "SCENARIO_AUDIT"

    # Compliance Intelligence, Security Control Governance & Assurance (Sprint 11A)
    COMPLIANCE_FRAMEWORK_READ = "COMPLIANCE_FRAMEWORK_READ"
    COMPLIANCE_FRAMEWORK_MANAGE = "COMPLIANCE_FRAMEWORK_MANAGE"
    COMPLIANCE_CONTROL_READ = "COMPLIANCE_CONTROL_READ"
    COMPLIANCE_CONTROL_MANAGE = "COMPLIANCE_CONTROL_MANAGE"
    COMPLIANCE_EVALUATE = "COMPLIANCE_EVALUATE"
    COMPLIANCE_GAP_READ = "COMPLIANCE_GAP_READ"
    COMPLIANCE_FINDING_CREATE = "COMPLIANCE_FINDING_CREATE"
    COMPLIANCE_FINDING_REVIEW = "COMPLIANCE_FINDING_REVIEW"
    COMPLIANCE_POSTURE_READ = "COMPLIANCE_POSTURE_READ"
    COMPLIANCE_POSTURE_REVIEW = "COMPLIANCE_POSTURE_REVIEW"
    COMPLIANCE_PROVENANCE_READ = "COMPLIANCE_PROVENANCE_READ"
    COMPLIANCE_AUDIT = "COMPLIANCE_AUDIT"

    # Threat Intelligence Integration & Correlation (Sprint 11B)
    THREAT_INTELLIGENCE_READ = "THREAT_INTELLIGENCE_READ"
    THREAT_INTELLIGENCE_SOURCE_MANAGE = "THREAT_INTELLIGENCE_SOURCE_MANAGE"
    THREAT_INTELLIGENCE_INGEST = "THREAT_INTELLIGENCE_INGEST"
    THREAT_INDICATOR_MANAGE = "THREAT_INDICATOR_MANAGE"
    THREAT_ACTOR_MANAGE = "THREAT_ACTOR_MANAGE"
    THREAT_CAMPAIGN_MANAGE = "THREAT_CAMPAIGN_MANAGE"
    THREAT_MITRE_MAP = "THREAT_MITRE_MAP"
    THREAT_CORRELATION_READ = "THREAT_CORRELATION_READ"
    THREAT_CORRELATION_EXECUTE = "THREAT_CORRELATION_EXECUTE"
    THREAT_INTELLIGENCE_EVALUATE = "THREAT_INTELLIGENCE_EVALUATE"
    THREAT_INTELLIGENCE_PROVENANCE_READ = "THREAT_INTELLIGENCE_PROVENANCE_READ"
    THREAT_INTELLIGENCE_AUDIT = "THREAT_INTELLIGENCE_AUDIT"

    # Unified SOC Investigation & Security Case Management (Sprint 12A)
    INVESTIGATION_READ = "INVESTIGATION_READ"
    INVESTIGATION_CREATE = "INVESTIGATION_CREATE"
    INVESTIGATION_ASSIGN = "INVESTIGATION_ASSIGN"
    INVESTIGATION_ANALYZE = "INVESTIGATION_ANALYZE"
    INVESTIGATION_HYPOTHESIS_MANAGE = "INVESTIGATION_HYPOTHESIS_MANAGE"
    INVESTIGATION_FINDING_CREATE = "INVESTIGATION_FINDING_CREATE"
    INVESTIGATION_RESOLVE = "INVESTIGATION_RESOLVE"
    INVESTIGATION_REVIEW = "INVESTIGATION_REVIEW"
    INVESTIGATION_PROVENANCE_READ = "INVESTIGATION_PROVENANCE_READ"
    INVESTIGATION_AUDIT = "INVESTIGATION_AUDIT"

    # Security Analytics, Reporting & Evidence Intelligence (Sprint 12B)
    SECURITY_ANALYTICS_READ = "SECURITY_ANALYTICS_READ"
    SECURITY_ANALYTICS_EVALUATE = "SECURITY_ANALYTICS_EVALUATE"
    SECURITY_ANALYTICS_TREND_READ = "SECURITY_ANALYTICS_TREND_READ"
    SECURITY_ANALYTICS_INSIGHT_READ = "SECURITY_ANALYTICS_INSIGHT_READ"
    SECURITY_REPORT_CREATE = "SECURITY_REPORT_CREATE"
    SECURITY_REPORT_READ = "SECURITY_REPORT_READ"
    SECURITY_REPORT_VERIFY = "SECURITY_REPORT_VERIFY"
    SECURITY_EVIDENCE_PACKAGE_CREATE = "SECURITY_EVIDENCE_PACKAGE_CREATE"
    SECURITY_EVIDENCE_PACKAGE_READ = "SECURITY_EVIDENCE_PACKAGE_READ"
    SECURITY_EVIDENCE_PACKAGE_VERIFY = "SECURITY_EVIDENCE_PACKAGE_VERIFY"
    SECURITY_ANALYTICS_PROVENANCE_READ = "SECURITY_ANALYTICS_PROVENANCE_READ"
    SECURITY_ANALYTICS_AUDIT = "SECURITY_ANALYTICS_AUDIT"


# ── Centralized Role-Permission Matrix ──────────────────────────────────────────
ROLE_PERMISSIONS: Dict[Role, Set[Permission]] = {
    Role.ADMIN: {
        Permission.USER_READ,
        Permission.USER_MANAGE,
        Permission.EVIDENCE_INGEST,
        Permission.EVIDENCE_READ,
        Permission.EVENT_NORMALIZE,
        Permission.NORMALIZED_EVENT_READ,
        Permission.SEMANTIC_INTERPRET,
        Permission.SEMANTIC_POLICY_CREATE,
        Permission.SEMANTIC_POLICY_EDIT_DRAFT,
        Permission.SEMANTIC_POLICY_READ,
        Permission.SEMANTIC_POLICY_COMPARE,
        Permission.SEMANTIC_POLICY_SUBMIT,
        Permission.POLICY_REVIEW,
        Permission.POLICY_APPROVE,
        Permission.POLICY_REJECT,
        Permission.POLICY_ACTIVATE,
        Permission.GOVERNANCE_AUDIT_READ,
        Permission.DRIFT_ALERT_READ,
        Permission.AUDIT_READ,
        Permission.MERKLE_BATCH_CREATE,
        Permission.MERKLE_BATCH_READ,
        Permission.MERKLE_PROOF_READ,
        Permission.DETECTION_RULE_CREATE,
        Permission.DETECTION_RULE_READ,
        Permission.DETECTION_RULE_TRUST_EVALUATE,
        Permission.DETECTION_RULE_TRUST_READ,
        Permission.DETECTION_TRUST_ALERT_READ,
        Permission.DETECTION_RULE_VERSION_CREATE,
        Permission.DETECTION_RULE_VERSION_READ,
        Permission.DETECTION_RULE_SUBMIT_REVIEW,
        Permission.DETECTION_RULE_REVIEW,
        Permission.DETECTION_RULE_ACTIVATE,
        Permission.DETECTION_RULE_DISABLE,
        Permission.DETECTION_RULE_GOVERNANCE_READ,
        Permission.DETECTION_EXECUTE,
        Permission.DETECTION_EXECUTION_READ,
        Permission.RISK_CORRELATION_READ,
        Permission.RISK_CORRELATION_ANALYZE,
        Permission.REMEDIATION_READ,
        Permission.REMEDIATION_GENERATE,
        Permission.REMEDIATION_SIMULATE,
        Permission.REMEDIATION_MANAGE,
        Permission.INCIDENT_READ,
        Permission.INCIDENT_CREATE,
        Permission.INCIDENT_ASSIGN,
        Permission.INCIDENT_STATUS_UPDATE,
        Permission.INCIDENT_SIGNAL_LINK,
        Permission.INCIDENT_EVIDENCE_LINK,
        Permission.INCIDENT_FINDING_CREATE,
        Permission.INCIDENT_FINDING_REVIEW,
        Permission.INCIDENT_AUDIT_READ,
        Permission.INCIDENT_RESPONSE_READ,
        Permission.INCIDENT_RESPONSE_RECOMMEND,
        Permission.INCIDENT_CONTAINMENT_PROPOSE,
        Permission.INCIDENT_CONTAINMENT_REVIEW,
        Permission.INCIDENT_RESPONSE_EXECUTE,
        Permission.INCIDENT_RESPONSE_VERIFY,
        Permission.INCIDENT_RESPONSE_AUDIT,
        Permission.ASSURANCE_READ,
        Permission.ASSURANCE_EVALUATE,
        Permission.ASSURANCE_ALERT_READ,
        Permission.ASSURANCE_ALERT_TRIAGE,
        Permission.ASSURANCE_AUDIT,
        Permission.ASSURANCE_REMEDIATION_READ,
        Permission.ASSURANCE_REMEDIATION_CREATE,
        Permission.ASSURANCE_ROOT_CAUSE_ANALYZE,
        Permission.ASSURANCE_REMEDIATION_RECOMMEND,
        Permission.ASSURANCE_REMEDIATION_PLAN,
        Permission.ASSURANCE_REMEDIATION_REVIEW,
        Permission.ASSURANCE_REMEDIATION_EXECUTE,
        Permission.ASSURANCE_RECOVERY_VERIFY,
        Permission.ASSURANCE_RECOVERY_CONFIRM,
        Permission.ASSURANCE_REMEDIATION_AUDIT,
        Permission.EXECUTIVE_SECURITY_READ,
        Permission.EXECUTIVE_SECURITY_EVALUATE,
        Permission.EXECUTIVE_SECURITY_EXPLAIN,
        Permission.EXECUTIVE_SECURITY_TREND_READ,
        Permission.EXECUTIVE_SECURITY_PROVENANCE_READ,
        Permission.EXECUTIVE_SECURITY_AUDIT,
        Permission.SCENARIO_READ,
        Permission.SCENARIO_CREATE,
        Permission.SCENARIO_VERSION_MANAGE,
        Permission.SCENARIO_EXECUTE,
        Permission.SCENARIO_REPLAY,
        Permission.SCENARIO_VERIFY,
        Permission.SCENARIO_PROVENANCE_READ,
        Permission.SCENARIO_AUDIT,
        Permission.COMPLIANCE_FRAMEWORK_READ,
        Permission.COMPLIANCE_FRAMEWORK_MANAGE,
        Permission.COMPLIANCE_CONTROL_READ,
        Permission.COMPLIANCE_CONTROL_MANAGE,
        Permission.COMPLIANCE_EVALUATE,
        Permission.COMPLIANCE_GAP_READ,
        Permission.COMPLIANCE_FINDING_CREATE,
        Permission.COMPLIANCE_FINDING_REVIEW,
        Permission.COMPLIANCE_POSTURE_READ,
        Permission.COMPLIANCE_POSTURE_REVIEW,
        Permission.COMPLIANCE_PROVENANCE_READ,
        Permission.COMPLIANCE_AUDIT,
        Permission.THREAT_INTELLIGENCE_READ,
        Permission.THREAT_INTELLIGENCE_SOURCE_MANAGE,
        Permission.THREAT_INTELLIGENCE_INGEST,
        Permission.THREAT_INDICATOR_MANAGE,
        Permission.THREAT_ACTOR_MANAGE,
        Permission.THREAT_CAMPAIGN_MANAGE,
        Permission.THREAT_MITRE_MAP,
        Permission.THREAT_CORRELATION_READ,
        Permission.THREAT_CORRELATION_EXECUTE,
        Permission.THREAT_INTELLIGENCE_EVALUATE,
        Permission.THREAT_INTELLIGENCE_PROVENANCE_READ,
        Permission.THREAT_INTELLIGENCE_AUDIT,
        Permission.INVESTIGATION_READ,
        Permission.INVESTIGATION_CREATE,
        Permission.INVESTIGATION_ASSIGN,
        Permission.INVESTIGATION_ANALYZE,
        Permission.INVESTIGATION_HYPOTHESIS_MANAGE,
        Permission.INVESTIGATION_FINDING_CREATE,
        Permission.INVESTIGATION_RESOLVE,
        Permission.INVESTIGATION_REVIEW,
        Permission.INVESTIGATION_PROVENANCE_READ,
        Permission.INVESTIGATION_AUDIT,
        Permission.SECURITY_ANALYTICS_READ,
        Permission.SECURITY_ANALYTICS_EVALUATE,
        Permission.SECURITY_ANALYTICS_TREND_READ,
        Permission.SECURITY_ANALYTICS_INSIGHT_READ,
        Permission.SECURITY_REPORT_CREATE,
        Permission.SECURITY_REPORT_READ,
        Permission.SECURITY_REPORT_VERIFY,
        Permission.SECURITY_EVIDENCE_PACKAGE_CREATE,
        Permission.SECURITY_EVIDENCE_PACKAGE_READ,
        Permission.SECURITY_EVIDENCE_PACKAGE_VERIFY,
        Permission.SECURITY_ANALYTICS_PROVENANCE_READ,
        Permission.SECURITY_ANALYTICS_AUDIT,
    },
    Role.POLICY_AUTHOR: {
        Permission.SEMANTIC_POLICY_CREATE,
        Permission.SEMANTIC_POLICY_EDIT_DRAFT,
        Permission.SEMANTIC_POLICY_READ,
        Permission.SEMANTIC_POLICY_COMPARE,
        Permission.SEMANTIC_POLICY_SUBMIT,
        Permission.NORMALIZED_EVENT_READ,
        Permission.DRIFT_ALERT_READ,
        Permission.GOVERNANCE_AUDIT_READ,
        Permission.MERKLE_BATCH_READ,
        Permission.DETECTION_RULE_CREATE,
        Permission.DETECTION_RULE_READ,
        Permission.DETECTION_RULE_TRUST_READ,
        Permission.DETECTION_RULE_VERSION_CREATE,
        Permission.DETECTION_RULE_VERSION_READ,
        Permission.DETECTION_RULE_SUBMIT_REVIEW,
        Permission.DETECTION_RULE_GOVERNANCE_READ,
        Permission.DETECTION_EXECUTION_READ,
        Permission.RISK_CORRELATION_READ,
        Permission.REMEDIATION_READ,
        Permission.INCIDENT_READ,
        Permission.INCIDENT_RESPONSE_READ,
        Permission.ASSURANCE_READ,
        Permission.ASSURANCE_REMEDIATION_READ,
        Permission.ASSURANCE_REMEDIATION_PLAN,
        Permission.EXECUTIVE_SECURITY_READ,
        Permission.SCENARIO_READ,
        Permission.SCENARIO_CREATE,
        Permission.SCENARIO_VERSION_MANAGE,
        Permission.COMPLIANCE_FRAMEWORK_READ,
        Permission.COMPLIANCE_FRAMEWORK_MANAGE,
        Permission.COMPLIANCE_CONTROL_READ,
        Permission.COMPLIANCE_CONTROL_MANAGE,
        Permission.COMPLIANCE_GAP_READ,
        Permission.COMPLIANCE_FINDING_CREATE,
        Permission.COMPLIANCE_POSTURE_READ,
        Permission.COMPLIANCE_PROVENANCE_READ,
        Permission.THREAT_INTELLIGENCE_READ,
        Permission.THREAT_INTELLIGENCE_SOURCE_MANAGE,
        Permission.THREAT_INDICATOR_MANAGE,
        Permission.THREAT_ACTOR_MANAGE,
        Permission.THREAT_CAMPAIGN_MANAGE,
        Permission.THREAT_MITRE_MAP,
        Permission.THREAT_CORRELATION_READ,
        Permission.THREAT_INTELLIGENCE_PROVENANCE_READ,
        Permission.INVESTIGATION_READ,
        Permission.INVESTIGATION_ANALYZE,
        Permission.INVESTIGATION_HYPOTHESIS_MANAGE,
        Permission.INVESTIGATION_FINDING_CREATE,
        Permission.INVESTIGATION_PROVENANCE_READ,
        Permission.SECURITY_ANALYTICS_READ,
        Permission.SECURITY_REPORT_READ,
        Permission.SECURITY_EVIDENCE_PACKAGE_READ,
    },
    Role.POLICY_REVIEWER: {
        Permission.SEMANTIC_POLICY_READ,
        Permission.SEMANTIC_POLICY_COMPARE,
        Permission.POLICY_REVIEW,
        Permission.POLICY_APPROVE,
        Permission.POLICY_REJECT,
        Permission.POLICY_ACTIVATE,
        Permission.GOVERNANCE_AUDIT_READ,
        Permission.DRIFT_ALERT_READ,
        Permission.NORMALIZED_EVENT_READ,
        Permission.AUDIT_READ,
        Permission.MERKLE_BATCH_READ,
        Permission.MERKLE_PROOF_READ,
        Permission.DETECTION_RULE_READ,
        Permission.DETECTION_RULE_TRUST_EVALUATE,
        Permission.DETECTION_RULE_TRUST_READ,
        Permission.DETECTION_TRUST_ALERT_READ,
        Permission.DETECTION_RULE_VERSION_READ,
        Permission.DETECTION_RULE_REVIEW,
        Permission.DETECTION_RULE_GOVERNANCE_READ,
        Permission.DETECTION_EXECUTION_READ,
        Permission.RISK_CORRELATION_READ,
        Permission.RISK_CORRELATION_ANALYZE,
        Permission.REMEDIATION_READ,
        Permission.REMEDIATION_SIMULATE,
        Permission.INCIDENT_READ,
        Permission.INCIDENT_FINDING_CREATE,
        Permission.INCIDENT_RESPONSE_READ,
        Permission.INCIDENT_CONTAINMENT_REVIEW,
        Permission.ASSURANCE_READ,
        Permission.ASSURANCE_EVALUATE,
        Permission.ASSURANCE_ALERT_READ,
        Permission.ASSURANCE_REMEDIATION_READ,
        Permission.ASSURANCE_ROOT_CAUSE_ANALYZE,
        Permission.ASSURANCE_REMEDIATION_REVIEW,
        Permission.ASSURANCE_RECOVERY_VERIFY,
        Permission.EXECUTIVE_SECURITY_READ,
        Permission.EXECUTIVE_SECURITY_EXPLAIN,
        Permission.SCENARIO_READ,
        Permission.SCENARIO_VERSION_MANAGE,
        Permission.SCENARIO_VERIFY,
        Permission.SCENARIO_PROVENANCE_READ,
        Permission.COMPLIANCE_FRAMEWORK_READ,
        Permission.COMPLIANCE_CONTROL_READ,
        Permission.COMPLIANCE_FINDING_REVIEW,
        Permission.COMPLIANCE_POSTURE_READ,
        Permission.COMPLIANCE_POSTURE_REVIEW,
        Permission.COMPLIANCE_PROVENANCE_READ,
        Permission.THREAT_INTELLIGENCE_READ,
        Permission.THREAT_CORRELATION_READ,
        Permission.THREAT_INTELLIGENCE_EVALUATE,
        Permission.THREAT_INTELLIGENCE_PROVENANCE_READ,
        Permission.INVESTIGATION_READ,
        Permission.INVESTIGATION_REVIEW,
        Permission.INVESTIGATION_PROVENANCE_READ,
        Permission.INVESTIGATION_AUDIT,
        Permission.SECURITY_ANALYTICS_READ,
        Permission.SECURITY_ANALYTICS_TREND_READ,
        Permission.SECURITY_ANALYTICS_INSIGHT_READ,
        Permission.SECURITY_REPORT_READ,
        Permission.SECURITY_REPORT_VERIFY,
        Permission.SECURITY_EVIDENCE_PACKAGE_READ,
        Permission.SECURITY_EVIDENCE_PACKAGE_VERIFY,
        Permission.SECURITY_ANALYTICS_PROVENANCE_READ,
    },
    Role.SECURITY_ANALYST: {
        Permission.EVIDENCE_INGEST,
        Permission.EVIDENCE_READ,
        Permission.EVENT_NORMALIZE,
        Permission.NORMALIZED_EVENT_READ,
        Permission.SEMANTIC_INTERPRET,
        Permission.SEMANTIC_POLICY_READ,
        Permission.SEMANTIC_POLICY_COMPARE,
        Permission.DRIFT_ALERT_READ,
        Permission.AUDIT_READ,
        Permission.GOVERNANCE_AUDIT_READ,
        Permission.MERKLE_BATCH_READ,
        Permission.MERKLE_PROOF_READ,
        Permission.DETECTION_RULE_CREATE,
        Permission.DETECTION_RULE_READ,
        Permission.DETECTION_RULE_TRUST_EVALUATE,
        Permission.DETECTION_RULE_TRUST_READ,
        Permission.DETECTION_TRUST_ALERT_READ,
        Permission.DETECTION_RULE_VERSION_READ,
        Permission.DETECTION_RULE_GOVERNANCE_READ,
        Permission.DETECTION_EXECUTE,
        Permission.DETECTION_EXECUTION_READ,
        Permission.RISK_CORRELATION_READ,
        Permission.RISK_CORRELATION_ANALYZE,
        Permission.REMEDIATION_READ,
        Permission.REMEDIATION_GENERATE,
        Permission.REMEDIATION_SIMULATE,
        Permission.REMEDIATION_MANAGE,
        Permission.INCIDENT_READ,
        Permission.INCIDENT_CREATE,
        Permission.INCIDENT_ASSIGN,
        Permission.INCIDENT_STATUS_UPDATE,
        Permission.INCIDENT_SIGNAL_LINK,
        Permission.INCIDENT_EVIDENCE_LINK,
        Permission.INCIDENT_FINDING_CREATE,
        Permission.INCIDENT_RESPONSE_READ,
        Permission.INCIDENT_RESPONSE_RECOMMEND,
        Permission.INCIDENT_CONTAINMENT_PROPOSE,
        Permission.INCIDENT_RESPONSE_EXECUTE,
        Permission.INCIDENT_RESPONSE_VERIFY,
        Permission.ASSURANCE_READ,
        Permission.ASSURANCE_EVALUATE,
        Permission.ASSURANCE_ALERT_READ,
        Permission.ASSURANCE_ALERT_TRIAGE,
        Permission.ASSURANCE_REMEDIATION_READ,
        Permission.ASSURANCE_REMEDIATION_CREATE,
        Permission.ASSURANCE_ROOT_CAUSE_ANALYZE,
        Permission.ASSURANCE_REMEDIATION_RECOMMEND,
        Permission.ASSURANCE_REMEDIATION_PLAN,
        Permission.ASSURANCE_REMEDIATION_EXECUTE,
        Permission.ASSURANCE_RECOVERY_VERIFY,
        Permission.EXECUTIVE_SECURITY_READ,
        Permission.EXECUTIVE_SECURITY_EVALUATE,
        Permission.EXECUTIVE_SECURITY_EXPLAIN,
        Permission.EXECUTIVE_SECURITY_TREND_READ,
        Permission.EXECUTIVE_SECURITY_PROVENANCE_READ,
        Permission.SCENARIO_READ,
        Permission.SCENARIO_EXECUTE,
        Permission.SCENARIO_REPLAY,
        Permission.SCENARIO_VERIFY,
        Permission.SCENARIO_PROVENANCE_READ,
        Permission.COMPLIANCE_FRAMEWORK_READ,
        Permission.COMPLIANCE_CONTROL_READ,
        Permission.COMPLIANCE_EVALUATE,
        Permission.COMPLIANCE_GAP_READ,
        Permission.COMPLIANCE_FINDING_CREATE,
        Permission.COMPLIANCE_POSTURE_READ,
        Permission.COMPLIANCE_PROVENANCE_READ,
        Permission.THREAT_INTELLIGENCE_READ,
        Permission.THREAT_INTELLIGENCE_INGEST,
        Permission.THREAT_INDICATOR_MANAGE,
        Permission.THREAT_ACTOR_MANAGE,
        Permission.THREAT_CAMPAIGN_MANAGE,
        Permission.THREAT_MITRE_MAP,
        Permission.THREAT_CORRELATION_READ,
        Permission.THREAT_CORRELATION_EXECUTE,
        Permission.THREAT_INTELLIGENCE_EVALUATE,
        Permission.THREAT_INTELLIGENCE_PROVENANCE_READ,
        Permission.INVESTIGATION_READ,
        Permission.INVESTIGATION_CREATE,
        Permission.INVESTIGATION_ASSIGN,
        Permission.INVESTIGATION_ANALYZE,
        Permission.INVESTIGATION_HYPOTHESIS_MANAGE,
        Permission.INVESTIGATION_FINDING_CREATE,
        Permission.INVESTIGATION_RESOLVE,
        Permission.INVESTIGATION_PROVENANCE_READ,
        Permission.SECURITY_ANALYTICS_READ,
        Permission.SECURITY_ANALYTICS_EVALUATE,
        Permission.SECURITY_ANALYTICS_TREND_READ,
        Permission.SECURITY_ANALYTICS_INSIGHT_READ,
        Permission.SECURITY_REPORT_CREATE,
        Permission.SECURITY_REPORT_READ,
        Permission.SECURITY_EVIDENCE_PACKAGE_CREATE,
        Permission.SECURITY_EVIDENCE_PACKAGE_READ,
        Permission.SECURITY_ANALYTICS_PROVENANCE_READ,
    },
    Role.AUDITOR: {
        Permission.EVIDENCE_READ,
        Permission.NORMALIZED_EVENT_READ,
        Permission.SEMANTIC_POLICY_READ,
        Permission.SEMANTIC_POLICY_COMPARE,
        Permission.POLICY_REVIEW,
        Permission.GOVERNANCE_AUDIT_READ,
        Permission.DRIFT_ALERT_READ,
        Permission.AUDIT_READ,
        Permission.USER_READ,
        Permission.MERKLE_BATCH_READ,
        Permission.MERKLE_PROOF_READ,
        Permission.DETECTION_RULE_READ,
        Permission.DETECTION_RULE_TRUST_READ,
        Permission.DETECTION_TRUST_ALERT_READ,
        Permission.DETECTION_RULE_VERSION_READ,
        Permission.DETECTION_RULE_GOVERNANCE_READ,
        Permission.DETECTION_EXECUTION_READ,
        Permission.RISK_CORRELATION_READ,
        Permission.REMEDIATION_READ,
        Permission.REMEDIATION_SIMULATE,
        Permission.INCIDENT_READ,
        Permission.INCIDENT_AUDIT_READ,
        Permission.INCIDENT_RESPONSE_READ,
        Permission.INCIDENT_RESPONSE_AUDIT,
        Permission.ASSURANCE_READ,
        Permission.ASSURANCE_AUDIT,
        Permission.ASSURANCE_ALERT_READ,
        Permission.ASSURANCE_REMEDIATION_READ,
        Permission.ASSURANCE_REMEDIATION_AUDIT,
        Permission.ASSURANCE_RECOVERY_VERIFY,
        Permission.EXECUTIVE_SECURITY_READ,
        Permission.EXECUTIVE_SECURITY_EXPLAIN,
        Permission.EXECUTIVE_SECURITY_TREND_READ,
        Permission.EXECUTIVE_SECURITY_PROVENANCE_READ,
        Permission.EXECUTIVE_SECURITY_AUDIT,
        Permission.SCENARIO_READ,
        Permission.SCENARIO_PROVENANCE_READ,
        Permission.SCENARIO_AUDIT,
        Permission.COMPLIANCE_FRAMEWORK_READ,
        Permission.COMPLIANCE_CONTROL_READ,
        Permission.COMPLIANCE_GAP_READ,
        Permission.COMPLIANCE_FINDING_REVIEW,
        Permission.COMPLIANCE_POSTURE_READ,
        Permission.COMPLIANCE_PROVENANCE_READ,
        Permission.COMPLIANCE_AUDIT,
        Permission.THREAT_INTELLIGENCE_READ,
        Permission.THREAT_CORRELATION_READ,
        Permission.THREAT_INTELLIGENCE_PROVENANCE_READ,
        Permission.THREAT_INTELLIGENCE_AUDIT,
        Permission.INVESTIGATION_READ,
        Permission.INVESTIGATION_PROVENANCE_READ,
        Permission.INVESTIGATION_AUDIT,
        Permission.SECURITY_ANALYTICS_READ,
        Permission.SECURITY_REPORT_READ,
        Permission.SECURITY_REPORT_VERIFY,
        Permission.SECURITY_EVIDENCE_PACKAGE_READ,
        Permission.SECURITY_EVIDENCE_PACKAGE_VERIFY,
        Permission.SECURITY_ANALYTICS_PROVENANCE_READ,
        Permission.SECURITY_ANALYTICS_AUDIT,
    },
    Role.VIEWER: {
        Permission.NORMALIZED_EVENT_READ,
        Permission.SEMANTIC_POLICY_READ,
        Permission.DRIFT_ALERT_READ,
        Permission.MERKLE_BATCH_READ,
        Permission.DETECTION_RULE_READ,
        Permission.DETECTION_RULE_TRUST_READ,
        Permission.DETECTION_RULE_VERSION_READ,
        Permission.RISK_CORRELATION_READ,
        Permission.REMEDIATION_READ,
        Permission.INCIDENT_READ,
        Permission.INCIDENT_RESPONSE_READ,
        Permission.ASSURANCE_READ,
        Permission.ASSURANCE_REMEDIATION_READ,
        Permission.EXECUTIVE_SECURITY_READ,
        Permission.SCENARIO_READ,
        Permission.COMPLIANCE_POSTURE_READ,
        Permission.THREAT_INTELLIGENCE_READ,
        Permission.THREAT_CORRELATION_READ,
        Permission.INVESTIGATION_READ,
        Permission.SECURITY_ANALYTICS_READ,
        Permission.SECURITY_REPORT_READ,
        Permission.SECURITY_EVIDENCE_PACKAGE_READ,
        Permission.SECURITY_ANALYTICS_TREND_READ,
        Permission.SECURITY_ANALYTICS_INSIGHT_READ,
        Permission.SECURITY_ANALYTICS_PROVENANCE_READ,
    },
}


def has_permission(role: str, permission: str) -> bool:
    """
    Evaluates whether a role possesses the specified permission.
    """
    try:
        role_enum = Role(role.upper())
        perm_enum = Permission(permission.upper())
    except (ValueError, AttributeError):
        return False

    return perm_enum in ROLE_PERMISSIONS.get(role_enum, set())


def get_permissions_for_role(role: str) -> List[str]:
    """
    Returns the list of string permission names granted to a role.
    """
    try:
        role_enum = Role(role.upper())
        return sorted([p.value for p in ROLE_PERMISSIONS.get(role_enum, set())])
    except (ValueError, AttributeError):
        return []
